# -*- coding: utf-8 -*-
"""Conditional_Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfbJWcudjlF40Gb1sPkb-au21l-a1U84
"""

#The logic of if, else, and elif statements is to execute specific blocks of code based on whether a condition or a series of conditions are true or false.
#if: Checks a condition; if true, executes its code block.
#elif: (short for "else if") If the preceding if or elif conditions were false, it checks a new condition; if true, executes its code block.
#else: If all preceding if and elif conditions were false, it executes its code block as the default action.

## if-elif-else condition
Number1 = int(input("The fist number is: "))
Number2 = int(input("The second number is: "))
Sum = Number1 + Number2
if Sum > 60:
  print("The sum is more than 60")
elif Sum < 60:
  print("The sum is less than 60")
else:
  print("The sum is equal to 60")

##Output :
#The fist number is: 66
#The second number is: 22
#The sum is more than 60

DefaultValue = 7000
Value1 = int(input("The value is: "))
if Value1 == DefaultValue:
  print("The DefaultValue is same as Value1")
elif Value1 > DefaultValue:
  print("The DefaultValue is smaller")
else:
  print("The DefaultValue is larger")


#output:
#The first value is: 3000
#The DefaultValue is larger

#Write method for significantly simpler than trying to find the largest number all at once, by comparing all possible pairs of numbers
#(i.e., first with second, second with third, third with first). Try to rebuild the code for yourself.
Num1 = int(input("The first num is: "))
Num2 = int(input("The second num is: "))
Num3 = int(input("The third num is: "))

if Num1 > Num2 and Num1 > Num3:
  print("The Num1 is larger number")
elif Num2 > Num1 and Num2 > Num3:
  print("The Num2 is larger number")
else:
  print("The Num3 is larger number")

##Output :
#The first num is: 15
#The second num is: 20
#The third num is: 18
#The Num2 is larger number

#Write a code to identify the plantname with upper and lower letters
Caps_Plantname = "Spathiphyllum"
Small_Plantname = "spathiphyllum"
FamousPlant = str(input("The FamousPlant name is :"))
if FamousPlant == Caps_Plantname:
  print("Yes - Spathiphyllum is the best plant ever!")
elif FamousPlant == Small_Plantname:
  print("No, I want a big Spathiphyllum!")
else:
  print("Spathiphyllum! Not", FamousPlant)
#Output
#The FamousPlant name is :bougenvilla
#Spathiphyllum! Not bougenvilla


# Write a code to detect the leap year
Year = int(input("The year of =  "))
if Year < 1582:
  print("Not within the Gregorian calendar period")
else:
  if Year % 4 != 0:
    print("It's a common year")
  elif Year % 400 != 0:
    print("It's a common year")
  elif Year % 100 != 0:
    print("It's a leap year")
  else:
    print("Its a leap year")

  #Output
  #The year of = 2008
  #It's a common year